// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:tech_restore/firebase_options.dart';



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';

/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8RWPJjaOg5Qi87HqKos_JQ9zikZC82DM',
    appId: '1:79705890213:web:3fd604182fecb9fb3cdc4c',
    messagingSenderId: '79705890213',
    projectId: 'tech-restore',
    authDomain: 'tech-restore.firebaseapp.com',
    storageBucket: 'tech-restore.firebasestorage.app',
    measurementId: 'G-5LWSJ79WWK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlC6sJ156WhyFL_KyVVSV9LFOduUa9UBw',
    appId: '1:79705890213:ios:edbbc067c4e308c43cdc4c',
    messagingSenderId: '79705890213',
    projectId: 'tech-restore',
    storageBucket: 'tech-restore.firebasestorage.app',
    iosClientId: '79705890213-vtrvrbr2gvgs0hpm9nhisfk525qqnqpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.techRestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlC6sJ156WhyFL_KyVVSV9LFOduUa9UBw',
    appId: '1:79705890213:ios:edbbc067c4e308c43cdc4c',
    messagingSenderId: '79705890213',
    projectId: 'tech-restore',
    storageBucket: 'tech-restore.firebasestorage.app',
    iosClientId: '79705890213-vtrvrbr2gvgs0hpm9nhisfk525qqnqpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.techRestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8RWPJjaOg5Qi87HqKos_JQ9zikZC82DM',
    appId: '1:79705890213:web:48fb0b11061bcca23cdc4c',
    messagingSenderId: '79705890213',
    projectId: 'tech-restore',
    authDomain: 'tech-restore.firebaseapp.com',
    storageBucket: 'tech-restore.firebasestorage.app',
    measurementId: 'G-3P2JZR5FWR',
  );
}
